naive_preprocessor1:
  class: preprocessor.naive.NaivePreprocessor1
  args:
    default_arg1: 1
    default_arg2: 2
    arg3: 3
  
naive_preprocessor2:
  class: preprocessor.naive.NaivePreprocessor2
  args:
    default_arg1: 1
    default_arg2: 2
    arg3: 3